services:
  postgres:
    image: postgres:15
    container_name: ghana_charities
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: gh_charities
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
