export enum FeaturesEnum {
    // Campaign
    CAN_VIEW_CAMPAIGN = 'CAN_VIEW_CAMPAIGN',
    CAN_CREATE_CAMPAIGN = 'CAN_CREATE_CAMPAIGN',
    CAN_EDIT_CAMPAIGN = 'CAN_EDIT_CAMPAIGN',
    CAN_DELETE_CAMPAIGN = 'CAN_DELETE_CAMPAIGN',

    // Donation
    CAN_VIEW_DONATIONS = 'CAN_VIEW_DONATIONS',
    CAN_EXPORT_DONATIONS = 'CAN_EXPORT_DONATIONS',

    // Event
    CAN_CREATE_EVENT = 'CAN_CREATE_EVENT',
    CAN_EDIT_EVENT = 'CAN_EDIT_EVENT',
    CAN_DELETE_EVENT = 'CAN_DELETE_EVENT',

    // Charity profile
    CAN_EDIT_CHARITY = 'CAN_EDIT_CHARITY',
    CAN_MANAGE_LOGO = 'CAN_MANAGE_LOGO',

    // Users & roles
    CAN_INVITE_USER = 'CAN_INVITE_USER',
    CAN_ASSIGN_ROLE = 'CAN_ASSIGN_ROLE',

    // Feature flags
    CAN_ACCESS_BETA_FEATURES = 'CAN_ACCESS_BETA_FEATURES'
}
